package hk.com.caretech.clive.idata_android;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import androidx.annotation.Nullable;

import java.sql.Timestamp;

import hk.com.caretech.clive.idata_android.Utils.SyncStatus;

public class SQLiteDBHelper extends SQLiteOpenHelper {

    public static final String DB_NAME = "idata";
    public static final String TABLE_TEMP = "temperature";
    public static final String COLUMN_ELDER_ID = "elder_id";
    public static final String COLUMN_TEMP = "temperature";
    public static final String COLUMN_DEVICE_ID = "device_id";
    public static final String COLUMN_TIMESTAMP = "timestamp";
    public static final String COLUMN_STATUS = "status";


    //database version
    private static final int DB_VERSION = 1;

    public SQLiteDBHelper(@Nullable Context context) {
        super(context, DB_NAME, null, DB_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        final String sql = " CREATE TABLE IF NOT EXISTS " + TABLE_TEMP
                + "( "
                + COLUMN_ELDER_ID + " INTEGER NOT NULL, "
                + COLUMN_TEMP + " DOUBLE NOT NULL, "
                + COLUMN_DEVICE_ID + " VARCHAR NOT NULL, "
                + COLUMN_TIMESTAMP + " TIMESTAMP NOT NULL, "
                + COLUMN_STATUS + " INTEGER NOT NULL, "
        + " PRIMARY KEY (" + COLUMN_DEVICE_ID + ", " + COLUMN_TIMESTAMP +")"
                +");";

        db.execSQL(sql);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        String sql = " DROP TABLE IF EXISTS "+ TABLE_TEMP;
        db.execSQL(sql);
    }



    /*
     * This method is taking four arguments
     * temp is "temperature" measured by thermometer
     * elder_id is the id of elders collected from server or manually input by user
     * device_id is the unique id of device generated by android system
     * status has two posible values:
     * 1 means the name is synced with the server
     * 0 means the name is not synced with the server
     * */
    public boolean addData(int elder_id, double temp, String device_id, int status) {
        SQLiteDatabase db = this.getWritableDatabase();

        ContentValues contentValues = new ContentValues();
        contentValues.put(COLUMN_ELDER_ID, elder_id);
        contentValues.put(COLUMN_TEMP, temp);
        contentValues.put(COLUMN_DEVICE_ID, device_id);
        contentValues.put(COLUMN_TIMESTAMP, System.currentTimeMillis());
        contentValues.put(COLUMN_STATUS, status);
        Log.i(TAG, "check added timestamp :" +System.currentTimeMillis());
        db.insert(TABLE_TEMP, null, contentValues);
        db.close();
        Log.i(TAG, "addTemp");
        return true;
    }

    /*
     * This method taking two arguments
     * first one is the temp_id of the temperature for which
     * we have to update the sync status
     * and the second one is the status that will be changed
     * */
    public void updateDataStatusToSync(String device_id, String timestamp) {
        SQLiteDatabase db = this.getWritableDatabase();
        ContentValues contentValues = new ContentValues();
        contentValues.put(COLUMN_STATUS, SyncStatus.SYNCHONISED);
        String whereQuery = COLUMN_DEVICE_ID + " = '" + device_id + "' AND " + COLUMN_TIMESTAMP + " = '" + timestamp + "'";
        //String query = "update "+TABLE_TEMP+" set "+COLUMN_STATUS+"="+1+" where "+COLUMN_DEVICE_ID+"='"+device_id+"' AND "+COLUMN_TIMESTAMP+"='"+timestamp+"'";
        //db.execSQL(query);
        db.update(TABLE_TEMP, contentValues, whereQuery, null);
        Log.i(TAG, "updateDataStatusToSync : update ran");
        db.close();
    }

    /*
     * this method will give us all the temps stored in sqlite
     * */
    public Cursor getData() {
        SQLiteDatabase db = this.getReadableDatabase();
        String sql = " SELECT * FROM " + TABLE_TEMP + " ORDER BY " + COLUMN_TIMESTAMP + " DESC;";
        Cursor c = db.rawQuery(sql, null);
        return c;
    }

    /*
     * this method is for getting all the unsynced temps
     * so that we can sync it with database
     * */
    public Cursor getUnsyncedData() {
        SQLiteDatabase db = this.getReadableDatabase();
        String sql = "SELECT * FROM " + TABLE_TEMP + " WHERE " + COLUMN_STATUS + " = 0;";
        Cursor c = db.rawQuery(sql, null);
        return c;
    }



    public int deleteAllLocalData()
    {
        SQLiteDatabase sqLiteDatabase=getWritableDatabase();
        int rowDeleted=sqLiteDatabase.delete(TABLE_TEMP,null,null);
        return rowDeleted;
    }

    static String TAG =SQLiteDBHelper.class.getName();
}
